version: 0.1.{build}

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  - ps: Install-Product node 9 x64
  - set CI=true
  - git reset --hard HEAD
  - npm install npm -g
  - npm install grunt-cli -g
  - npm install

build_script:
  - node --version
  - npm --version
  - grunt dist

before_deploy:
  - mkdir apps\installers
  - npm run deploy-appveyor

deploy:
  description: 'Space Invader-v$(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: GGWpP6cibMdB2Q9L41M3GBz4KEQILhjiI+gXJtKlD1YkMmGMW0DlF7g6JdYg3znT
  artifact:
    apps/installers/spaceinvader-win32-ia32.zip
    apps/installers/spaceinvader-win32-x64.zip
    apps/installers/spaceinvader-*-setup.msi
  draft: false
  prerelease: false
  appveyor_repo_tag: true        # deploy on tag push only

test: off
